version: '3'

vars:
  PROJECT_NAME: Thumbp

tasks:
  compile:
    desc: Compile sources (with Rust)
    env:
      RUSTLER_PRECOMPILATION_EXAMPLE_BUILD: 1
    cmds:
      - mix compile

  compile-using-precompiled-binaries:
    desc: Compile sources (without Rust)
    cmds:
      - mix compile

  console:
    desc: Open console
    env:
      RUSTLER_PRECOMPILATION_EXAMPLE_BUILD: 1
    cmds:
      - cmd: iex -S mix
        ignore_error: true

  test:
    desc: Run tests (with Rust)
    env:
      RUSTLER_PRECOMPILATION_EXAMPLE_BUILD: 1
    cmds:
      - mix test --trace

  test-using-precompiled-binaries:
    desc: Run tests (without Rust)
    cmds:
      - mix test --trace

  check:
    desc: Check codes
    cmds:
      - task: dialyzer
      - task: clippy

  dialyzer:
    desc: Run dialyzer
    cmd: mix dialyzer

  clippy:
    desc: Run clippy
    dir: native/thumbp
    cmd: cargo clippy

  clean:
    desc: Clean up
    cmds:
      - mix clean
      - rm -f priv/native/*.so

  benchmark:
    desc: Run benchmark
    cmd: mix run benchmark/benchmark.exs

  rustler-precompiled-download:
    desc: Download precompiled files info
    env:
      RUSTLER_PRECOMPILATION_EXAMPLE_BUILD: 1
    cmds:
      - "mix rustler_precompiled.download {{.PROJECT_NAME}} --all --print"

  default:
    cmds:
      - task -l --sort=none
    silent: true
